# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: LCAx
site_author: Christian Kongsgaard
site_description: "The goal for LCAx is to make an open, machine and human-readable data format for exchanging LCA results, EPD's and assemblies."
site_url: "https://lcax.kongsgaard.eu"
theme:
  name: material
  custom_dir: 'docs/overrides'
  palette:
    - scheme: chrkong
  font:
    text: Roboto
markdown_extensions:
  - mdx_include:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/ocni-dtu/lcax
nav:
  - LCAx: index.md
  - Data Structure: data_structure.md
  - Schemas: schemas.md
  - Examples: examples.md
extra:
  generator: false
  social:
    - icon: octicons/globe-24
      link: https://kongsgaard.eu
      name: Christian Kongsgaard ApS
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/christian-kongsgaard/
  analytics:
    provider: custom
extra_css:
  - stylesheets/extra.css
copyright: Christian Kongsgaard ApS
